//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Shared.Resources.Errors {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Shared.Resources.Errors.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 金额不能小于等于 0 的本地化字符串。
        /// </summary>
        public static string AmountInvalid {
            get {
                return ResourceManager.GetString("AmountInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 币种不匹配 的本地化字符串。
        /// </summary>
        public static string CurrencyMismatch {
            get {
                return ResourceManager.GetString("CurrencyMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据格式无效 的本地化字符串。
        /// </summary>
        public static string InvalidDataFormat {
            get {
                return ResourceManager.GetString("InvalidDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期范围无效 (开始时间 &gt; 结束时间) 的本地化字符串。
        /// </summary>
        public static string InvalidDateRange {
            get {
                return ResourceManager.GetString("InvalidDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不允许的状态转换 的本地化字符串。
        /// </summary>
        public static string InvalidStateTransition {
            get {
                return ResourceManager.GetString("InvalidStateTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必填项不能为空 的本地化字符串。
        /// </summary>
        public static string RequiredValueNotEmpty {
            get {
                return ResourceManager.GetString("RequiredValueNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符串长度超出限制 的本地化字符串。
        /// </summary>
        public static string StringLengthExceeded {
            get {
                return ResourceManager.GetString("StringLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数值超出允许范围 的本地化字符串。
        /// </summary>
        public static string ValueOutOfRange {
            get {
                return ResourceManager.GetString("ValueOutOfRange", resourceCulture);
            }
        }
    }
}
